name: Main

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cargo-all-features
      - run: cargo check-all-features --bin '*_soln'
      - run: cargo check-all-features --bin 'macrokata'
      - run: cargo check-all-features release --bin '*_soln'
      - run: cargo check-all-features release --bin 'macrokata'

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cargo-all-features
      - run: cargo build-all-features --bin '*_soln'
      - run: cargo build-all-features --bin 'macrokata'
      - run: cargo build-all-features release --bin '*_soln'
      - run: cargo build-all-features release --bin 'macrokata'

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cargo-all-features
      - run: cargo test-all-features --bin '*_soln'
      - run: cargo test-all-features --bin 'macrokata'
      - run: cargo test-all-features release --bin '*_soln'
      - run: cargo test-all-features release --bin 'macrokata'

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: rustup component add clippy
      - run: cargo clippy --bin '*_soln' -- -D warnings
      - run: cargo clippy --bin 'macrokata' -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: rustup component add rustfmt
      - run: cargo fmt --check
